// Original practice questions. Each answer has a primary-source reading link.
const refs={
 iguala:'https://inehrm.gob.mx/recursos/Libros/Antologia_de_lecturas_200_t2.pdf',
 cordoba:'https://inehrm.gob.mx/recursos/Libros/Los_tratados_de_Cordoba.pdf',
 ayutla:'https://www.gob.mx/agricultura/dgsiap/es/articulos/plan-de-ayutla',
 celaya:'https://www.gob.mx/defensa/documentos/6-de-abril-de-1915-batalla-de-celaya?state=published',
 tratado:'https://www.archives.gov/milestone-documents/treaty-of-guadalupe-hidalgo',
 fuentes:'https://www.gob.mx/cultura/prensa/carlos-fuentes-su-literatura-se-nutrio-de-una-nacion-y-dio-dimension-universal-al-imaginario-de-lo-mexicano?idiom=es',
 garro:'https://www.gob.mx/cultura/articulos/elena-garro-entre-magia-fantasia-surrealismo-y-realidad',
 castellanos:'https://catalogoradioeducacion.cultura.gob.mx/series/balun-canan/',
 mural:'https://www.gob.mx/cultura/prensa/jose-clemente-orozco-uno-de-los-pilares-del-muralismo-mexicano',
 publico:'https://www.gob.mx/cultura/articulos/a-un-siglo-del-muralismo',
 siqueiros:'https://www.gob.mx/cultura/prensa/david-alfaro-siqueiros-artista-que-renovo-los-canones-de-la-pintura?idiom=es-MX',
 guelaguetza:'https://www.gob.mx/cultura/articulos/la-guelaguetza-o-la-fiesta-de-la-comunalidad-de-los-pueblos-de-oaxaca?idiom=es',
 tajin:'https://www.inah.gob.mx/zonas/153-zona-arqueologica-el-tajin-y-museo-de-sitio',
 tula:'https://inah.gob.mx/boletines/tula-ciudad-de-quetzalcoatl',
 paquime:'https://lugares.inah.gob.mx/es/node/4353',
 sian:'https://www.gob.mx/conanp/articulos/reserva-de-la-biosfera-sian-ka-an-hogar-del-jaguar?state=published',
 humedales:'https://www.gob.mx/semarnat/es/articulos/reserva-de-la-biosfera-sian-ka-an-sitio-de-grandes-humedales?idiom=es'
};
const rows=[
 [6,'Historia','¿Cuáles fueron las tres garantías del Plan de Iguala?','Religión, independencia y unión|Tierra, trabajo y libertad|Educación, salud y vivienda|República, laicidad y sufragio','Las garantías nombraron al Ejército Trigarante.','iguala'],
 [6,'Historia','¿Quiénes firmaron los Tratados de Córdoba?','Agustín de Iturbide y Juan O’Donojú|Hidalgo y Morelos|Juárez y Maximiliano|Madero y Zapata','Iturbide y O’Donojú los suscribieron en 1821.','cordoba'],
 [6,'Historia','¿En qué fecha se firmaron los Tratados de Córdoba?','24 de agosto de 1821|16 de septiembre de 1810|5 de febrero de 1857|20 de noviembre de 1910','La firma precedió a la entrada del Ejército Trigarante en la capital.','cordoba'],
 [6,'Historia','¿Contra qué gobernante se dirigió el Plan de Ayutla?','Antonio López de Santa Anna|Porfirio Díaz|Victoriano Huerta|Venustiano Carranza','El movimiento de Ayutla buscó terminar con la dictadura de Santa Anna.','ayutla'],
 [6,'Historia','¿En qué año se proclamó el Plan de Ayutla?','1854|1821|1911|1938','Ayutla antecedió al Constituyente que elaboró la Constitución de 1857.','ayutla'],
 [6,'Historia','¿Qué proceso constitucional siguió al triunfo de Ayutla?','La elaboración de la Constitución de 1857|La Constitución de Cádiz de 1812|La fundación de Nueva España|La Constitución de Apatzingán de 1814','El movimiento abrió paso al Congreso Constituyente liberal.','ayutla'],
 [6,'Historia','¿Qué tratado puso fin a la guerra entre México y Estados Unidos de 1846–1848?','Guadalupe Hidalgo|Córdoba|Versalles|Tordesillas','El tratado de paz se firmó el 2 de febrero de 1848.','tratado'],
 [6,'Historia','¿Qué mandos se enfrentaron en Celaya en 1915?','Álvaro Obregón y Francisco Villa|Hidalgo e Iturbide|Juárez y Zaragoza|Cárdenas y Madero','Las fuerzas de Obregón derrotaron a las villistas.','celaya'],
 [6,'Historia','¿Qué bando fue derrotado en la primera batalla de Celaya de abril de 1915?','El encabezado por Francisco Villa|El de Álvaro Obregón|El ejército de Ignacio Zaragoza|El de Miguel Hidalgo','La defensa de Obregón frenó el avance de Villa.','celaya'],
 [6,'Historia','¿Qué orden cronológico es correcto?','Córdoba → Guadalupe Hidalgo → Ayutla|Ayutla → Córdoba → Guadalupe Hidalgo|Guadalupe Hidalgo → Ayutla → Córdoba|Córdoba → Ayutla → Guadalupe Hidalgo','1821, 1848 y 1854, respectivamente. Distingue consumación, guerra internacional y reforma liberal.','ayutla'],
 [7,'Literatura','¿Quién escribió Aura?','Carlos Fuentes|Juan Rulfo|Octavio Paz|José Emilio Pacheco','La novela corta de Fuentes apareció en 1962.','fuentes'],
 [7,'Literatura','¿Qué novela de Carlos Fuentes lleva el nombre de un personaje que recuerda su vida?','La muerte de Artemio Cruz|Balún Canán|Los recuerdos del porvenir|Pedro Páramo','La muerte de Artemio Cruz es una novela de Fuentes publicada en 1962.','fuentes'],
 [7,'Literatura','¿Quién es la autora de Los recuerdos del porvenir?','Elena Garro|Rosario Castellanos|Sor Juana Inés de la Cruz|Nellie Campobello','La novela de Elena Garro apareció en 1963.','garro'],
 [7,'Literatura','¿Cuál de estas novelas fue escrita por Rosario Castellanos?','Balún Canán|Aura|Pedro Páramo|Los recuerdos del porvenir','Castellanos es la autora de Balún Canán.','castellanos'],
 [7,'Arte','Además de Rivera y Siqueiros, ¿quién integra los llamados tres grandes del muralismo?','José Clemente Orozco|Manuel M. Ponce|José Alfredo Jiménez|Juan Rulfo','Orozco es una de las figuras centrales del muralismo mexicano.','mural'],
 [7,'Arte','¿Qué recinto fue escenario de los primeros murales del movimiento mexicano?','Antiguo Colegio de San Ildefonso|Castillo de Windsor|Palacio de Versalles|Museo del Prado','La antigua Escuela Nacional Preparatoria acogió el trabajo de diversos muralistas.','publico'],
 [7,'Arte','¿Qué educador impulsó el proyecto cultural asociado al muralismo posrevolucionario?','José Vasconcelos|Agustín de Iturbide|Antonio López de Santa Anna|Juan O’Donojú','Vasconcelos vinculó arte, cultura y educación popular.','publico'],
 [7,'Arte','¿Con qué artista se relaciona La Tallera, en Cuernavaca?','David Alfaro Siqueiros|Juan Rulfo|Rosario Castellanos|Elena Garro','La Tallera fue el taller de producción de Siqueiros.','siqueiros'],
 [7,'Tradiciones','¿En qué estado se celebra la Guelaguetza?','Oaxaca|Sonora|Coahuila|Nuevo León','Es una celebración de las comunidades y culturas de Oaxaca.','guelaguetza'],
 [7,'Tradiciones','¿Qué vínculo comunitario está en el origen del concepto de guelaguetza?','La ayuda mutua|La sucesión monárquica|El servicio militar obligatorio|El aislamiento entre pueblos','Su sentido comunitario remite al intercambio y apoyo entre personas y pueblos.','guelaguetza'],
 [8,'Patrimonio','¿En qué zona arqueológica está la Pirámide de los Nichos?','El Tajín|Tula|Paquimé|Monte Albán','La Pirámide de los Nichos es un edificio emblemático de El Tajín.','tajin'],
 [8,'Patrimonio','¿Cuántos nichos dan su particular simbolismo solar a esa pirámide de El Tajín?','365|52|20|260','El INAH registra 365 nichos, relacionados simbólicamente con el calendario solar.','tajin'],
 [8,'Geografía','¿En qué estado se localiza El Tajín?','Veracruz|Hidalgo|Chihuahua|Yucatán','El Tajín se encuentra en el norte de Veracruz.','tajin'],
 [8,'Patrimonio','¿Qué sitio es especialmente conocido por sus atlantes toltecas?','Tula|Palenque|Paquimé|El Tajín','Los atlantes son esculturas características de Tula.','tula'],
 [8,'Geografía','¿En qué estado se encuentra la zona arqueológica de Tula?','Hidalgo|Tlaxcala|Chiapas|Durango','Tula se localiza en Hidalgo, al norte de la Ciudad de México.','tula'],
 [8,'Geografía','¿Qué estado alberga Paquimé?','Chihuahua|Quintana Roo|Morelos|Puebla','Paquimé está en Casas Grandes, Chihuahua.','paquime'],
 [8,'Patrimonio','¿Con qué región geográfica se relaciona Paquimé?','Desierto Chihuahuense|Selva Lacandona|Península de Yucatán|Costa del Pacífico sur','Su contexto geográfico es el norte desértico del país.','paquime'],
 [8,'Naturaleza','¿Dónde está la Reserva de la Biosfera Sian Ka’an?','Quintana Roo|Baja California|Zacatecas|Aguascalientes','Sian Ka’an está en el Caribe mexicano, en Quintana Roo.','sian'],
 [8,'Naturaleza','¿Qué combinación de ecosistemas se encuentra en Sian Ka’an?','Selvas y arrecifes de coral|Tundra y glaciares|Taiga y fiordos polares|Desierto helado y estepa ártica','La reserva conserva ecosistemas terrestres y marinos.','sian'],
 [8,'Naturaleza','¿Qué elementos conecta el sistema subterráneo de agua dulce de Sian Ka’an?','Cenotes y petenes|Glaciares y fiordos|Minas de carbón y volcanes|Salinas y campos de hielo','Los humedales y conexiones de agua dulce son parte esencial de esta reserva.','humedales']
];
export const advancedQuestions=rows.map(([level,topic,text,options,explanation,ref],i)=>({id:`a${i+1}`,level,topic,text,options:options.split('|'),explanation,source:refs[ref]}));
