import {advancedQuestions} from './advanced.js';
import {extraQuestions} from './extra.js';
export const levels = [
 ['Explorador','Las raíces de México','México en el mundo, su territorio y su gente.'],
 ['Aprendiz','Un viaje por nuestra historia','De la Independencia a la Revolución.'],
 ['Conocedor','México se escribe y se celebra','Cultura, patrimonio y tradiciones.'],
 ['Avanzado','La vida en común','Democracia, instituciones y derechos.'],
 ['Experto','Conecta las piezas','Relaciona hechos y afina los detalles.'],
 ['Historiador','Más allá de las fechas','Etapa 2 · Tratados y conflictos.'],
 ['Intérprete','Las voces de México','Etapa 2 · Literatura, arte y tradiciones.'],
 ['Especialista','Un país por descubrir','Etapa 2 · Patrimonio y naturaleza.']
];
// Banco original de práctica; no reproduce ni predice el banco reservado de la SRE.
// En cada fila la primera opción es correcta. El motor aleatoriza su posición.
const rows = [
 [1,'Geografía','¿Cuál es la capital de México?','Ciudad de México|Guadalajara|Monterrey|Puebla','La Ciudad de México es la capital del país.'],
 [1,'Geografía','¿Qué océano limita con México al oeste?','Pacífico|Atlántico|Índico|Ártico','El litoral occidental mexicano se encuentra en el Pacífico.'],
 [1,'Geografía','¿Qué países tienen frontera terrestre con México al sureste?','Guatemala y Belice|Honduras y Panamá|Cuba y Guatemala|Belice y Costa Rica','Guatemala y Belice son sus vecinos terrestres del sureste.'],
 [1,'Geografía','¿Cuál es la capital de Yucatán?','Mérida|Campeche|Cancún|Chetumal','Mérida es la capital de Yucatán; Cancún está en Quintana Roo.'],
 [1,'Geografía','¿En qué estado está Guadalajara?','Jalisco|Puebla|Sonora|Veracruz','Guadalajara es la capital de Jalisco.'],
 [1,'Geografía','¿Qué península se encuentra al noroeste de México?','Baja California|Yucatán|Florida|Osa','La península de Baja California está entre el Pacífico y el golfo de California.'],
 [1,'Geografía','¿Qué país colinda con México al norte?','Estados Unidos|Canadá|Guatemala|Belice','La frontera norte de México es con Estados Unidos.'],
 [1,'Geografía','¿Cuál es la capital de Nuevo León?','Monterrey|Saltillo|Durango|Tepic','Monterrey es la capital de Nuevo León.'],
 [1,'Geografía','¿En qué estado se encuentra Teziutlán?','Puebla|Tlaxcala|Hidalgo|Oaxaca','Teziutlán es un municipio del estado de Puebla.'],
 [1,'Geografía','¿Cuál de estos estados está en la península de Yucatán?','Quintana Roo|Nayarit|Colima|Zacatecas','Quintana Roo forma parte de la península de Yucatán.'],
 [1,'Geografía','¿Qué mar baña la costa de Quintana Roo?','Caribe|Mediterráneo|Rojo|Báltico','Quintana Roo tiene costa sobre el mar Caribe.'],
 [1,'Geografía','¿Qué estado tiene como capital a Xalapa?','Veracruz|Tabasco|Chiapas|Campeche','Xalapa es la capital de Veracruz.'],
 [1,'Geografía','¿Cuál es la capital de Oaxaca?','Oaxaca de Juárez|Tuxtla Gutiérrez|Chilpancingo|Villahermosa','Oaxaca de Juárez es la capital del estado del mismo nombre.'],
 [1,'Geografía','¿Qué cuerpo de agua separa la península de Baja California del continente?','Golfo de California|Golfo de México|Mar Caribe|Lago de Chapala','El golfo de California también es conocido como mar de Cortés.'],
 [1,'Geografía','¿Cuál de estas ciudades está en el estado de Guanajuato?','León|Morelia|Toluca|Cuernavaca','León pertenece a Guanajuato; Morelia es la capital de Michoacán.'],
 [2,'Historia','¿Qué se conmemora el 16 de septiembre?','Inicio de la Independencia|Consumación de la Independencia|Batalla de Puebla|Promulgación de la Constitución','El movimiento independentista comenzó en 1810.'],
 [2,'Historia','¿Quién inició el movimiento de Independencia con el Grito de Dolores?','Miguel Hidalgo|Benito Juárez|Francisco I. Madero|Lázaro Cárdenas','Miguel Hidalgo llamó al levantamiento en Dolores en 1810.'],
 [2,'Historia','¿En qué año se consumó la Independencia de México?','1821|1810|1857|1910','El Ejército Trigarante entró en la capital en 1821.'],
 [2,'Historia','¿Quién escribió Sentimientos de la Nación?','José María Morelos|Porfirio Díaz|Vicente Guerrero|Emiliano Zapata','Morelos presentó ese documento en 1813.'],
 [2,'Historia','¿Qué se conmemora el 5 de mayo?','Batalla de Puebla de 1862|Inicio de la Revolución|Independencia de 1821|Constitución de 1917','El ejército mexicano derrotó a fuerzas francesas en Puebla.'],
 [2,'Historia','¿Quién comandó al ejército mexicano en la Batalla de Puebla?','Ignacio Zaragoza|Agustín de Iturbide|Álvaro Obregón|Venustiano Carranza','Ignacio Zaragoza dirigió la defensa mexicana el 5 de mayo de 1862.'],
 [2,'Historia','¿Con qué personaje se asocia el periodo llamado Porfiriato?','Porfirio Díaz|Benito Juárez|Antonio López de Santa Anna|Francisco Villa','El nombre alude al prolongado predominio político de Porfirio Díaz.'],
 [2,'Historia','¿En qué año comenzó la Revolución mexicana?','1910|1810|1862|1938','La convocatoria del Plan de San Luis fijó el levantamiento para el 20 de noviembre de 1910.'],
 [2,'Historia','¿Quién impulsó el Plan de San Luis?','Francisco I. Madero|Emiliano Zapata|Lázaro Cárdenas|José María Morelos','Madero convocó a luchar contra el régimen de Porfirio Díaz.'],
 [2,'Historia','¿Qué demanda destaca en el Plan de Ayala?','Restitución de tierras|Restauración de la monarquía|Creación de un virreinato|Anexión a Estados Unidos','El plan zapatista puso la cuestión agraria en el centro.'],
 [2,'Historia','¿En qué ciudad se promulgó la Constitución de 1917?','Querétaro|Ciudad de México|Puebla|Guadalajara','Querétaro fue la sede del Congreso Constituyente.'],
 [2,'Historia','¿Qué presidente decretó la expropiación petrolera en 1938?','Lázaro Cárdenas|Porfirio Díaz|Francisco I. Madero|Miguel Alemán','Cárdenas anunció la expropiación el 18 de marzo de 1938.'],
 [2,'Historia','¿Qué presidente se asocia con las Leyes de Reforma?','Benito Juárez|Vicente Fox|Guadalupe Victoria|Plutarco Elías Calles','Juárez es figura central del proceso liberal de Reforma.'],
 [2,'Historia','¿Cuál fue el primer presidente de México?','Guadalupe Victoria|Miguel Hidalgo|Agustín de Iturbide|Benito Juárez','Guadalupe Victoria fue el primer presidente de la república.'],
 [2,'Historia','¿Qué fecha conmemora la Constitución de 1917?','5 de febrero|24 de febrero|21 de marzo|20 de noviembre','La Constitución fue promulgada el 5 de febrero de 1917.'],
 [3,'Cultura','¿Quién escribió Pedro Páramo?','Juan Rulfo|Octavio Paz|Carlos Fuentes|José Emilio Pacheco','Pedro Páramo es una novela de Juan Rulfo.'],
 [3,'Cultura','¿Quién fue Sor Juana Inés de la Cruz?','Escritora y religiosa novohispana|Presidenta de México|Pintora del siglo XX|General revolucionaria','Sor Juana destacó en la literatura del periodo virreinal.'],
 [3,'Patrimonio','¿Con qué cultura se relaciona principalmente Monte Albán?','Zapoteca|Mexica|Totonaca|Purépecha','Monte Albán fue una importante capital zapoteca en Oaxaca.'],
 [3,'Patrimonio','¿A qué civilización pertenece Chichén Itzá?','Maya|Olmeca|Purépecha|Romana','Chichén Itzá es una ciudad maya en Yucatán.'],
 [3,'Cultura','¿Qué pintora es conocida por sus autorretratos y la Casa Azul?','Frida Kahlo|Remedios Varo|Leonora Carrington|María Izquierdo','La Casa Azul está vinculada con la vida de Frida Kahlo.'],
 [3,'Cultura','¿Quién recibió el Nobel de Literatura en 1990?','Octavio Paz|Juan Rulfo|Diego Rivera|Alfonso Reyes','Octavio Paz recibió el Nobel de Literatura en 1990.'],
 [3,'Cultura','¿Quién escribió la letra del Himno Nacional Mexicano?','Francisco González Bocanegra|Jaime Nunó|Amado Nervo|Manuel M. Ponce','González Bocanegra escribió la letra; Jaime Nunó compuso la música.'],
 [3,'Cultura','¿Quién compuso la música del Himno Nacional?','Jaime Nunó|Francisco González Bocanegra|José Alfredo Jiménez|Agustín Lara','Jaime Nunó es el compositor de la música del himno.'],
 [3,'Cultura','¿Qué representa el Día de Muertos?','El recuerdo y homenaje a los difuntos|El inicio de la Independencia|Una elección federal|La fundación de Puebla','Las ofrendas son parte de las diversas maneras de recordar a los difuntos.'],
 [3,'Cultura','¿Cuál de estos alimentos tiene al maíz como base tradicional?','Tortilla|Pan de trigo|Cuscús|Pasta de sémola','La tortilla de maíz es fundamental en numerosas cocinas mexicanas.'],
 [3,'Cultura','¿Cuál de estos artistas fue muralista mexicano?','Diego Rivera|Pablo Neruda|Jorge Luis Borges|Gabriel García Márquez','Diego Rivera destacó en el muralismo mexicano.'],
 [3,'Patrimonio','¿En qué estado se encuentra Palenque?','Chiapas|Sonora|Durango|Aguascalientes','Palenque es una zona arqueológica maya de Chiapas.'],
 [3,'Cultura','¿Qué flor se asocia especialmente con las ofrendas de Día de Muertos?','Cempasúchil|Tulipán|Lavanda|Edelweiss','El cempasúchil es habitual en las ofrendas, aunque las tradiciones varían por región.'],
 [3,'Patrimonio','¿Cuál fue la capital del imperio mexica?','México-Tenochtitlan|Palenque|Monte Albán|Tula','México-Tenochtitlan se estableció en el lago de Texcoco.'],
 [3,'Cultura','¿Qué se conmemora en México el 24 de febrero?','Día de la Bandera|Día de la Independencia|Día de la Revolución|Día del Trabajo','El 24 de febrero es el Día de la Bandera.'],
 [4,'Civismo','¿Cuáles son los tres poderes de la Federación?','Legislativo, Ejecutivo y Judicial|Federal, estatal y municipal|Civil, militar y religioso|Presidencia, ejército y policía','Son poderes, no órdenes de gobierno. Artículo 49.'],
 [4,'Civismo','¿Qué cámaras integran el Congreso de la Unión?','Diputados y Senadores|Ministros y Gobernadores|Alcaldes y Diputados|Jueces y Senadores','El Legislativo federal es bicameral. Artículo 50.'],
 [4,'Civismo','¿En quién se deposita el Poder Ejecutivo federal?','La persona titular de la Presidencia|El Congreso de la Unión|La Suprema Corte|Los ayuntamientos','El Ejecutivo federal es unipersonal. Artículo 80.'],
 [4,'Civismo','¿En quién reside esencial y originariamente la soberanía nacional?','El pueblo|El ejército|Una familia real|Un gobierno extranjero','El artículo 39 reconoce al pueblo como origen de la soberanía.'],
 [4,'Civismo','¿Qué artículo constitucional trata del derecho a la educación?','3°|27|123|80','El artículo 3° desarrolla el derecho a la educación.'],
 [4,'Civismo','¿Qué artículo constitucional es fundamental para los derechos laborales?','123|3°|50|39','El artículo 123 regula trabajo y previsión social.'],
 [4,'Civismo','¿Qué significa que el Estado sea laico?','No adopta una religión oficial|Prohíbe toda creencia privada|Es gobernado por ministros de culto|Impone una religión a todos','La laicidad distingue las instituciones estatales de las religiosas.'],
 [4,'Civismo','¿Cuál es la base de la división territorial y organización política de los estados?','El municipio libre|La parroquia|El virreinato|El consulado','El artículo 115 establece el municipio libre como base.'],
 [4,'Civismo','¿Qué caracteriza a una república federal?','Entidades unidas en una federación|Poder hereditario absoluto|Gobierno de una iglesia|Ausencia de constitución','El federalismo distribuye competencias entre ámbitos de gobierno.'],
 [4,'Civismo','¿Qué implica el voto secreto?','No tener que revelar por quién se votó|Que nadie cuente los votos|Que sólo voten autoridades|Que el voto no tenga registro electoral','El secreto protege la libertad de elegir sin coacción.'],
 [4,'Civismo','¿Qué significa discriminación?','Trato excluyente que vulnera derechos|Toda diferencia de opinión|Cualquier elección personal|Respetar distintas creencias','La discriminación niega igualdad en el ejercicio de derechos.'],
 [4,'Civismo','¿Cuál es una forma pacífica de participación ciudadana?','Presentar propuestas a las autoridades|Amenazar a otros votantes|Comprar votos|Impedir el sufragio','Participar también incluye proponer y dialogar, no sólo votar.'],
 [4,'Civismo','¿Qué principio exige que la autoridad actúe conforme a normas?','Legalidad|Herencia dinástica|Censura absoluta|Arbitrariedad','La legalidad limita el ejercicio del poder público.'],
 [4,'Civismo','¿Cuál es una actitud compatible con la pluralidad cultural?','Respetar distintas lenguas y tradiciones|Exigir una sola tradición|Excluir por origen|Negar derechos por acento','La pluralidad reconoce la diversidad de la sociedad.'],
 [4,'Civismo','¿Cuál es una diferencia entre una ley y una opinión personal?','La ley es una norma emitida por autoridad competente|Toda opinión es obligatoria|La ley sólo expresa gustos|Las opiniones sustituyen la Constitución','Las normas jurídicas no dependen de gustos individuales.'],
 [5,'Historia','¿Cuál es el orden cronológico correcto?','Independencia, Reforma, Revolución|Revolución, Reforma, Independencia|Reforma, Independencia, Revolución|Independencia, Revolución, Reforma','Independencia: siglo XIX temprano; Reforma: mediados del XIX; Revolución: desde 1910.'],
 [5,'Historia','¿Qué distingue 1810 de 1821 en la Independencia?','Inicio del movimiento y consumación|Consumación e inicio|Dos constituciones|Dos intervenciones francesas','El proceso iniciado en 1810 culminó en 1821.'],
 [5,'Historia','¿Qué pareja de plan y dirigente es correcta?','Ayala — Emiliano Zapata|San Luis — Benito Juárez|Ayala — Porfirio Díaz|San Luis — Miguel Hidalgo','El Plan de Ayala está asociado al zapatismo.'],
 [5,'Civismo','Federal, estatal y municipal son…','Órdenes de gobierno|Los tres poderes federales|Las cámaras del Congreso|Tipos de ciudadanía','No deben confundirse con Ejecutivo, Legislativo y Judicial.'],
 [5,'Historia','¿Qué relación describe mejor la Reforma liberal?','Separación de asuntos civiles y eclesiásticos|Restauración del virreinato|Inicio del imperio mexica|Abolición de la república','La Reforma fortaleció las instituciones civiles y el Estado laico.'],
 [5,'Historia','¿Qué personaje y acontecimiento corresponden?','Carranza — Constitución de 1917|Hidalgo — expropiación petrolera|Cárdenas — Grito de Dolores|Juárez — inicio de la Revolución','Carranza promulgó la Constitución surgida del Constituyente.'],
 [5,'Patrimonio','¿Qué asociación de sitio y cultura es correcta?','Monte Albán — zapoteca|Palenque — romana|Chichén Itzá — mexica|Tenochtitlan — inca','Monte Albán fue capital zapoteca; Palenque y Chichén Itzá son mayas.'],
 [5,'Cultura','¿Qué asociación de autor y obra es correcta?','Juan Rulfo — Pedro Páramo|Octavio Paz — Pedro Páramo|Diego Rivera — El llano en llamas|Frida Kahlo — El laberinto de la soledad','Rulfo escribió Pedro Páramo y El llano en llamas.'],
 [5,'Historia','¿Cuál de estos sucesos ocurrió primero?','Batalla de Puebla|Revolución mexicana|Constitución de 1917|Expropiación petrolera','Puebla: 1862; Revolución: 1910; Constitución: 1917; expropiación: 1938.'],
 [5,'Geografía','¿Qué par de ciudad y estado es correcto?','Mérida — Yucatán|Cancún — Yucatán|Guadalajara — Guanajuato|Monterrey — Coahuila','Mérida es capital de Yucatán; Cancún pertenece a Quintana Roo.'],
 [5,'Civismo','Una persona afirma que Legislativo significa gobierno municipal. ¿Qué confunde?','Poderes con órdenes de gobierno|Estados con continentes|Derechos con idiomas|Municipios con océanos','Legislativo nombra un poder; municipal nombra un ámbito de gobierno.'],
 [5,'Historia','¿Qué diferencia al 5 de febrero del 5 de mayo?','Constitución de 1917 y Batalla de Puebla|Independencia y Revolución|Bandera y Trabajo|Dos fechas de la Independencia','Febrero recuerda la Constitución; mayo, la batalla de 1862.'],
 [5,'Cultura','¿Qué dos nombres corresponden al Himno Nacional?','González Bocanegra y Jaime Nunó|Juan Rulfo y Octavio Paz|Diego Rivera y Frida Kahlo|Hidalgo y Morelos','González Bocanegra: letra. Nunó: música.'],
 [5,'Historia','¿Qué secuencia va de más antigua a más reciente?','Tenochtitlan, Nueva España, México independiente|Nueva España, Tenochtitlan, México independiente|México independiente, Tenochtitlan, Nueva España|Tenochtitlan, México independiente, Nueva España','La capital mexica precedió al periodo virreinal y al México independiente.'],
 [5,'Civismo','Una autoridad obliga a alguien a revelar su voto. ¿Qué principio afecta?','Secreto del voto|Herencia del poder|Centralismo|Libertad de comercio','La elección debe poder mantenerse privada para proteger al votante.']
];
export const questions = rows.map(([level,topic,text,options,explanation],i)=>({id:`q${i+1}`,level,topic,text,options:options.split('|'),explanation})).concat(advancedQuestions,extraQuestions);
export const focusIds = ['q26','q46','q64'];
export const sources = [
 ['Guía de estudio de la SRE','Bibliografía oficial; úsala como referencia principal.','https://portales.sre.gob.mx/tramites-dgaj/naturalizacion/guia-de-estudios'],
 ['Formato del examen · SRE','Historia y cultura: 10 preguntas, mínimo 8 aciertos.','https://sre.gob.mx/tramites-y-servicios/nacionalidad-y-naturalizacion'],
 ['Constitución Política','Texto vigente para consultar los artículos constitucionales.','https://www.diputados.gob.mx/LeyesBiblio/pdf/CPEUM.pdf'],
 ['Constituyente de 1917 · INEHRM','Querétaro y el origen de la Constitución.','https://www.inehrm.gob.mx/es/Constitucion1917/Congreso_Constituyente_y_Constitucion_de_1917'],
 ['Monte Albán · INAH','La capital zapoteca y su patrimonio.','https://www.inah.gob.mx/foto-del-dia/la-traza-arquitectonica-de-monte-alban']
];
